- /220/assets/simplified/DianJiang/55.png
- /220/assets/simplified/DianJiang/56.png
- /220/assets/simplified/GeneralSkinPreview/15k.png
- /220/assets/winnerGeneral/full/18700.swf #王异第一个武将大图
- /220/assets/simplified/GeneralSkinPreview/18702p.png # 王异传说小图
- /220/assets/simplified/GeneralSkinPreview/18702p.swf # 王异传说动态
- /220/assets/videoskin/xinwangyi02Big.f4v #传说动态预览
- /220/assets/videoskin/xinwangyi02.swf # 传说动态牌局内
- /220/assets/videoskin/diaochan07.swf #替换成最新的貂蝉限定动态 牌局内   146x172
- /220/assets/videoskin/diaochan07Big.f4v #替换成最新的貂蝉限定动态 武将预览
